### ISSUE TITLE
std::fmt::Display / static str impl for Language enum?

### ISSUE THREAD

**Issue by philippeitis** [vv9k/mobi-rs#37]
It would be nice to have a method to return a static string for members of the Language enum (for representation purposes upstream), plus a corresponding std::fmt::Display method (which would use the static string method). This isn't super important, is in a sense "broken" from the 0.5 to 0.6 transition.

Potential crate:
https://docs.rs/strum_macros/0.23.1/strum_macros/derive.AsRefStr.html

**Comment by vv9k** [comment]
I'm not sure I'm keen on bringing this functionality back. I removed it on purpose as I felt like crate consumers should decide how the types are displayed. My reasoning was that perhaps some might want to display languages in their respective language rather than their english name so better not include it than add an opinionated default.

**Comment by philippeitis** [comment]
That seems perfectly reasonable. I suppose it would be nice to have some integration with a crate which would provide this functionality, but for the time being, it isn't a priority.

**Comment by vv9k** [comment]
Thanks for your understanding and I'm sorry about the breakage between 0.5 and 0.6. Next time a breaking change will happen it will be noted in the CHANGELOG as I added it recently. I'm gonna close this issue for now following my reasoning in the previous comment.
